version: '3'

services: 
    jenkins:
        image: jenkins/jenkins:jdk11
        container_name: jenkins
        ports:
        - "8880:8080"
        - "50000:50000"
        volumes:
        - ../volumes/jenkins:/var/jenkins_home
        networks: 
        - docker_network

    ubuntu:
        container_name: ubuntu1
        build:
          context: ../dockerfiles/slave
        volumes: 
        - /var/run/docker.sock:/var/run/docker.sock
        command: java -jar agent.jar -jnlpUrl http://192.168.44.44:8880/computer/Slave/slave-agent.jnlp -secret bb530a68378fbc56b00ef573ee218f8bfdf232ab0faf8ad59b0fcb80d65b0c1a -workDir "/home/"
        depends_on:
        - jenkins
        networks: 
        - docker_network

    artifactory:
        image: docker.bintray.io/jfrog/artifactory-oss:latest
        container_name: artifactory
        volumes: 
        - ../volumes/artifactory:/var/opt/jfrog/artifactory
        ports:
        - "8081:8081"
        - "8082:8082"
        networks:
        - docker_network
    selenum_hub:
        image: selenium/hub
        container_name: seleniunhub
        ports:
            - "4444:4444"
        networks:
        - docker_network 

    selenium_firefox:
        image: selenium/node-firefox
        container_name: firefox
        depends_on:
        - selenum_hub
        environment:
        - HUB_HOST=selenum_hub
        - HUB_PORT=4444
        networks:
        - docker_network

networks:
    docker_network:
        driver: bridge